name: Build website

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'

      - name: Gradle Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Build Docker Image
        run: docker build -t adepaul.dev .

      - name: Docker Hub Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker image tag adepaul.dev ${{ secrets.DOCKER_USERNAME }}/private:adepaul.dev
          docker image push ${{ secrets.DOCKER_USERNAME }}/private:adepaul.dev
