name: Build website

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'

      - name: Canister Login
        run: docker login --username=${{ secrets.CANISTER_ID }} --password=${{ secrets.CANISTER_PASSWORD }} cloud.canister.io:5000

      - name: Build Docker Image with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
          docker build -t adepaul.dev .

      - name: Push Docker Image to Registry
        run: |
          docker image tag adepaul.dev cloud.canister.io:5000/${{ secrets.CANISTER_ID }}/adepaul.dev
          docker image push cloud.canister.io:5000/${{ secrets.CANISTER_ID }}/adepaul.dev
