name: Build and deploy website

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'

      - name: Canister Login
        run: docker login --username=${{ secrets.CANISTER_ID }} --password=${{ secrets.CANISTER_PASSWORD }} cloud.canister.io:5000

      - name: Build Docker Image with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
          docker build -t adepaul.dev .

      - name: Push Docker Image to Registry
        run: |
          docker image tag adepaul.dev cloud.canister.io:5000/${{ secrets.CANISTER_ID }}/adepaul.dev
          docker image push cloud.canister.io:5000/${{ secrets.CANISTER_ID }}/adepaul.dev

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Canister Login
        run: podman login --username=${{ secrets.CANISTER_ID }} --password=${{ secrets.CANISTER_PASSWORD }} cloud.canister.io:5000

      - name: Remove old container and images
        run: |
          # https://stackoverflow.com/questions/34228864/stop-and-delete-docker-container-if-its-running
          podman ps -q --filter "name=adepaul-dev" | grep -q . && podman stop adepaul-dev && podman rm -f adepaul-dev
          # if the container is not running
          podman ps -aq --filter "name=adepaul-dev" | grep -q . && podman rm -f adepaul-dev
          podman image prune -af

      - name: Pull and Run Docker Image
        run: podman run --name adepaul-dev -d -p 8080:8080 cloud.canister.io:5000/${{ secrets.CANISTER_ID }}/adepaul.dev:latest
