name: Dependency Submission

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]

jobs:
  dependency-submission:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'corretto'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
